// <auto-generated />
using System;
using Infrastructure.Presistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // 1. Documents Table
            modelBuilder.Entity("Domain.Entities.Document", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("DeletedAtUtc").HasColumnType("datetime2");
                b.Property<string>("FileName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FilePath").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UpdatedBy").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Documents");
            });

            // 2. Podcast Table
            modelBuilder.Entity("Domain.Entities.Podcast", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("AudioPath").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("DeletedAtUtc").HasColumnType("datetime2");
                b.Property<Guid>("DocumentId").HasColumnType("uniqueidentifier");
                b.Property<int?>("EndPage").HasColumnType("int");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<int>("Mode").HasColumnType("int");
                b.Property<string>("ScriptPath").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int?>("StartPage").HasColumnType("int");
                b.Property<string>("Topic").HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UpdatedBy").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("DocumentId");
                b.ToTable("Podcast");
            });

            // 3. Identity & Users Tables (The Master Core)
            modelBuilder.Entity("Domain.Users.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Email").IsRequired().HasColumnName("Email").HasColumnType("nvarchar(max)");
                b.Property<string>("Username").IsRequired().HasColumnName("Username").HasColumnType("nvarchar(450)");
                b.Property<string>("IdentityId").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("DomainUsers", (string)null);
            });

            modelBuilder.Entity("Infrastructure.Identity.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.ToTable("AspNetUsers", (string)null);
            });

            // 4. Relationships
            modelBuilder.Entity("Domain.Entities.Podcast", b =>
            {
                b.HasOne("Domain.Entities.Document", "Document")
                    .WithMany("Podcasts")
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Document");
            });

            modelBuilder.Entity("Domain.Entities.Document", b =>
            {
                b.Navigation("Podcasts");
            });

#pragma warning restore 612, 618
        }
    }
}